application:
  name: Course Management Platform
  url: ${APPLICATION_URL:http://localhost:8080}
spring:
  debug:
    requests: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/courseplatform}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  flyway:
    locations: db.migration
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ## Cache properties
  freemarker.cache: false      #set false in development environment; It is false by default.
  thymeleaf.cache: false
  groovy.template.cache: false
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 150MB
      max-request-size: 200MB
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui-courses.html
    disable-swagger-default-url: true # Disable default redirect to /swagger-ui/index.html
    urls:
      - url: ${springdoc.api-docs.path}
        name: ${application.name}
  api-docs:
    enabled: true
    path: /api/v1/api-docs
    path-all: ${springdoc.api-docs.path}/**
  paths-to-match: /api/v1/**
security:
  jwt:
    access-token-expiration: ${SECURITY_JWT_ACCESS_TOKEN_EXPIRATION:36000000}
    refresh-token-expiration: ${SECURITY_JWT_REFRESH_TOKEN_EXPIRATION:864000000}
    signing-key: ${SECURITY_JWT_SIGNING_KEY:24432646294A404E635266556A586E5A7234753778214125442A472D4B615064}

