name: CI - Build Course API Backend

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: courseplatform
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
            token: ${{ secrets.github_token }}
            prefix: ${{ github.github.develop }}
      - run: |
          write-output $env:build_number
        env:
          build_number: ${{ steps.buildnumber.outputs.build_number }}
        shell: pwsh
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: 17
#          cache: maven
#      - name: Unit/Integration tests with Maven
#        run: mvn -ntp -B verify

